Wael_AbuRayya-nodejs-w2
HackYourHomework/Node.js-class39 pull request #17
Opened 2022-10-12 02:19 UTC by wael35nl

2022-10-15 13:47 UTC, mnvacym requested changes

2022-10-15 13:47 UTC, mnvacym commented on homework/hackyourtemperature/package.json
> +    "nodemon": "^2.0.20"
You don't need `nodemon` on production. You will be using it on your local development. So it'd be wise to install it in your devDependencies.

2022-10-15 13:47 UTC, mnvacym commented on homework/hackyourtemperature/__tests__/app.test.js
> +describe("app.post", async () => {
You need to use `async` for the function that you use `await`. In this case you need to use it for `it` function

2022-10-15 13:47 UTC, mnvacym commented on homework/hackyourtemperature/__tests__/app.test.js
> +  it("should return status code 200 if a valid city name is passed", () => {
Your test is failing. Please have a look. And also, please try to cover different response scenarios in your tests

2022-10-15 13:47 UTC, mnvacym commented on homework/hackyourtemperature/app.js
> +    res.sendStatus(500);
I think you can not send the status in `catch` block. Because if something is wrong with your API call, for example, if you do a bad request, this block will be run, and once this block is run, that means the headers are already baked in; you can not set them.

For example, if you hit this endpoint with `{"cityName": ""}`, you will get an error in your server console:
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

So you need to handle your responses in your then block with a condition, like you did

2022-10-15 13:47 UTC, mnvacym commented on homework/hackyourtemperature/app.js
> +      res.send({ weatherText: 'City is not found!' });
You need to add `return` below this line to exit the function. Since you don't have an if and else block, your code will continue running.

2022-10-15 13:47 UTC, mnvacym commented on homework/hackyourtemperature/app.js
> +    res.sendStatus(400);
It might be better to also send a descriptive message to client. Because now if a city is not provided it will only return `Bad Request`. Instead you can do for example:
`res.status(400).send("No city provided!");`

2022-10-15 13:49 UTC, mnvacym commented
Hi Wael,

Your test is failing. And please try to cover other scenarios in your tests.

I left some comments for your endpoints. Please have a look, and if anything is not clear, please do not hesitate to ask for help.

Kind regards,
Ammar Merakli

2022-10-15 14:06 UTC, mnvacym commented on homework/hackyourtemperature/app.js
> +    console.error(error);
Always try to send a response to the client. If you console something, your server's user will not see anything on the client side.

2022-10-16 02:23 UTC, wael35nl commented on homework/hackyourtemperature/package.json
> +    "nodemon": "^2.0.20"
Done!

2022-10-16 02:23 UTC, wael35nl commented on homework/hackyourtemperature/__tests__/app.test.js
> +describe("app.post", async () => {
Done!

2022-10-16 02:26 UTC, wael35nl commented on homework/hackyourtemperature/app.js
> +    res.sendStatus(500);
Ok, so no status sending in the catch, I added res.send(error.message), but can't guess, where can I see this response message?

2022-10-16 02:26 UTC, wael35nl commented on homework/hackyourtemperature/app.js
> +      res.send({ weatherText: 'City is not found!' });
I added it and tested the difference, thanks.
is this condition < if (localWeather.cod >= 400) > the right one to use in case of a wrong city name is passed in?

2022-10-16 02:26 UTC, wael35nl commented on homework/hackyourtemperature/app.js
> +    res.sendStatus(400);
Done!

2022-10-16 02:29 UTC, wael35nl commented on homework/hackyourtemperature/app.js
> +    console.error(error);
like this?
catch (error) {
console.error(error);
res.send(error.message);
}

2022-10-16 02:36 UTC, wael35nl commented on homework/hackyourtemperature/app.js
> +    console.error(error);
Thanks a lot for this very caring guiding.
and I'm actually a bit late with asking for help (or too late).
I appreciate your support and will let you know when this homework gets approved if there's still something unclear to me.

2022-10-16 02:37 UTC, wael35nl commented
Thanks a lot for this very caring guidance.
and I'm actually a bit late with asking for help (or too late).
I appreciate your support and will let you know when this homework gets approved if there's still something unclear to me.

2022-10-16 07:07 UTC, wael35nl commented on homework/hackyourtemperature/__tests__/app.test.js
> +  it("should return status code 200 if a valid city name is passed", () => {
Now it works, and hopefully I covered enough response scenarios...

2022-10-16 14:43 UTC, mnvacym commented on homework/hackyourtemperature/app.js
> +    res.sendStatus(500);
Actually if you want you can send status codes in catch block of course. But you can have only one send() per request. So if you want to send status code in catch block you need to make sure that your conditions in then/try block are met correctly. Because if a condition is met and there is something wrong with the code for example, send()/sendStatus() will be run twice.

2022-10-17 05:18 UTC, wael35nl commented on homework/hackyourtemperature/app.js
> +    res.sendStatus(500);
Ok, thanks.

Are the last changes good or there's still what I need to do?

2022-10-17 15:40 UTC, mnvacym commented on homework/hackyourtemperature/app.js
> +      res.send({ weatherText: 'City is not found!' });
I'll approve your PR now; just something just to keep in mind: it might be better if you precisely state status codes for your conditions. Like for example

```
if (localWeather.cod === 400) {
return ...
} 

if (localWeather.cod === 404) {
return ...
} 
```

2022-10-17 16:29 UTC, wael35nl commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
code
	{mso-style-priority:99;
	font-family:"Courier New";}
pre
	{mso-style-priority:99;
	mso-style-link:"HTML Preformatted Char";
	margin:0in;
	font-size:10.0pt;
	font-family:"Courier New";}
span.HTMLPreformattedChar
	{mso-style-name:"HTML Preformatted Char";
	mso-style-priority:99;
	mso-style-link:"HTML Preformatted";
	font-family:"Courier New";}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
-->Ok, I will test that.thanks Sent from Mail for Windows From: AmmarSent: Monday, October 17, 2022 5:40 PMTo: HackYourHomework/Node.js-class39Cc: Wael AbuRayya; AuthorSubject: Re: [HackYourHomework/Node.js-class39] Wael_AbuRayya-nodejs-w2 (PR ***@***.*** commented on this pull request.In homework/hackyourtemperature/app.js:> +});++app.post('/weather', async (req, res) => {+  const { city } = req.body;++  if (!city) {+    res.sendStatus(400);+    return;+  }++  try {+    const getWeather = await fetch(`https://api.openweathermap.org/data/2.5/weather?q=${city}&APPID=${keys.API_KEY}`);+    const localWeather = await getWeather.json();++    if (localWeather.cod >= 400) {+      res.send({ weatherText: 'City is not found!' });I'll approve your PR now; just something just to keep in mind: it might be better if you precisely state status codes for your conditions. Like for exampleif (localWeather.cod === 400) {return ...}  if (localWeather.cod === 404) {return ...} —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***> 

2022-12-04 02:59 UTC, closed without merging